// src/api/createCustomChallenge.js
import { createSupabaseServerClient, getUserFromBearer } from "../lib/supabaseServer.js";
import { getTemplate } from "../lib/challengeTemplates.js";

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ ok: false, error: "Method not allowed" });

  try {
    const supabase = createSupabaseServerClient();

    const authHeader = (req.headers.authorization || "").replace("Bearer ", "").trim();
    if (!authHeader) return res.status(401).json({ ok: false, error: "Missing Authorization" });

    const user = await getUserFromBearer(authHeader);
    if (!user) return res.status(401).json({ ok: false, error: "Invalid token" });

    const body = req.body || (req._body && req._body) || {};
    const { title, templateId, target } = body;

    if (!title || !templateId) return res.status(400).json({ ok: false, error: "title and templateId required" });

    const tpl = getTemplate(templateId);
    if (!tpl) return res.status(400).json({ ok: false, error: "Unknown templateId" });

    const row = {
      // id can be auto-generated by DB; include client id if preferred
      user_id: user.id,
      template_id: tpl.id,
      title: String(title).trim(),
      description: `Custom challenge — ${String(title).trim()}`,
      target: Number(target) || tpl.suggestedTarget || 1,
      progress: 0,
      status: "in_progress",
      xp: tpl.xp, // stored as canonical (optional)
      credits: tpl.credits, // stored as canonical (optional)
      created_at: new Date().toISOString(),
    };

    const { data, error } = await supabase.from("custom_challenges").insert([row]).select().maybeSingle();
    if (error) {
      console.error("createCustomChallenge insert error:", error);
      return res.status(500).json({ ok: false, error: "DB insert failed" });
    }

    return res.status(201).json({ ok: true, challenge: data });
  } catch (e) {
    console.error("createCustomChallenge error:", e);
    return res.status(500).json({ ok: false, error: "Server error" });
  }
}
